import Foundation

/// A scheduled programme on an ``EPGChannel``.
///
/// Decoded from the daily EPG JSON dump. `start`/`stop` are ISO-8601 instants;
/// the on-disk JSON is generated by `tvepg dump` with `dateEncodingStrategy = .iso8601`,
/// so ``EPGClient`` configures its decoder to match.
struct EPGProgramme: Codable, Sendable, Hashable, Identifiable {
    let channelID: String
    let title: String
    let subtitle: String?
    let description: String?
    let start: Date
    let stop: Date
    let categories: [String]

    /// Synthetic, derived from channel + start time. Stable across regenerations as long
    /// as the upstream feed keeps the same start instant for the same airing.
    var id: String { "\(channelID)|\(Int(start.timeIntervalSince1970))" }

    var duration: TimeInterval { stop.timeIntervalSince(start) }

    func isLive(at date: Date = .now) -> Bool {
        date >= start && date < stop
    }
}
